# Generated by Django 3.1.7 on 2021-03-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='00000000000', max_length=300, verbose_name='Телефон'),
        ),
    ]
