# Generated by Django 3.1.7 on 2021-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210303_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agreement',
            field=models.CharField(default=True, max_length=300, verbose_name='Согласие на отправку писем'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='Мужчина', max_length=1, verbose_name='Пол'),
        ),
    ]
