# Generated by Django 3.1.7 on 2021-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210303_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=True, max_length=300, verbose_name='Согласие на отправку писем'),
        ),
    ]
