# Generated by Django 3.1.7 on 2021-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210303_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=True, verbose_name='Согласие на отправку писем'),
        ),
    ]
