# Generated by Django 3.1.7 on 2021-03-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210303_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('famale', 'Женщина')], default='Мужчина', max_length=40, verbose_name='Пол'),
        ),
    ]
