# Generated by Django 3.1.7 on 2021-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210226_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='blog/images/post-default.jpg', upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Kivy', 'Kivy'), ('JavaScript', 'JavaScript'), ('HTML/CSS', 'HTML/CSS')], default='Python', max_length=10, verbose_name='Рубрика'),
        ),
    ]
